### ISSUE TITLE
ImageMagick location changes dependent on OS version

### ISSUE THREAD

**Issue by marsbard** [marsbard/puppet-alfresco#24]
On trusty it needs to be this: `img.coders=/usr/lib/ImageMagick-6.6.9/modules-Q16/coders`

However on precise64 (which the vagrant builds use) it should be: `img.coders=/usr/lib/x86_64-linux-gnu/ImageMagick-6.7.7/modules-Q16/coders`

Still not sure what it should be on centos 

Seems like the name of the package changed too, this works on precise to find the right path: `dpkg -L libmagickcore4 | grep coders | head -n1` but not on trusty as it uses libmagickcore5

So we need 2 custom facts I think:

First is to work out the package name (again only for debian-based, centos will need a different approach):

`apt-cache search magick | grep "libmagickcore. " | cut -d\  -f1` will return libmagickcore4 on precise and libmagickcore5 on trusty.

Then we can use that fact to do 
`dpkg -L <libmagickpkg> | grep coders | head -n1`

to retrieve the correct value of `img.coders`

**Comment by marsbard** [comment]
Facter docs for custom facts: https://docs.puppetlabs.com/facter/2.4/custom_facts.html

Where to install custom facts: https://docs.puppetlabs.com/guides/plugins_in_modules.html

**Comment by digcat** [comment]
pdf2swf in alfresco-global.properties is usr/local/bin on centos build this path needs to be /usr/bin 
also location of taskset is different for centos build, it needs to be /bin rather than usr/bin

Execution result: 
   os:         Linux
   command:    /opt/alfresco/bin/limitconvert.sh /opt/alfresco/tomcat/temp/Alfresco/ImageMagickContentTransformerWorker_init_source_3681833858496091486.gif /opt/alfresco/tomcat/temp/Alfresco/ImageMagickContentTransformerWorker_init_target_7069471979523260582.png
   succeeded:  true
   exit code:  127
   out:        
   err:        /opt/alfresco/bin/limitconvert.sh: line 13: /usr/bin/taskset: No such file or directory

**Comment by digcat** [comment]
pdf2swf in wrong place on ubuntu.  changed debiab back to usr/local/bin/pdf2swf, remove standard redhat swftools and use same build as ubuntu.
